In [1]:
from os.path import isdir
from os import listdir
from PIL import Image
import numpy as np
from tensorflow.keras.models import load_model

import CONSTANTS
from extract_features import get_embedding
from main5Celeb import convert_to_embeddings
from face_classification import train_SVM


Using TensorFlow backend.


In [4]:
def load_faces_from_dataset(data_dir, save_dir):
    tmp = 0
    X_train, y_train, X_test, y_test = list(),list(), list(), list()
    X, y = list(), list()
    tmp = 0
    for subdir in listdir(data_dir):
        faces = list() #save faces from subdir
        path = data_dir + subdir + '/'
        #skip file is not dir
        if not isdir(path):
            continue

        for item in listdir(path):
            file = path + item
            img = Image.open(file)
            img = img.convert('RGB')
            img = img.resize((160, 160))
            pixels = np.asarray(img)
            faces.append(pixels)
            # list_faces_of_person (np.array_face)
        
        X.append(faces)  #list_of_persons( list (nparray))
        y.append(subdir)

        tmp += 1
        if tmp > 10:
            break
    return X, y

In [5]:
data_dir = CONSTANTS.root + '/data/VNCeleb-dataset/'
X, y =  load_faces_from_dataset(
        CONSTANTS.VNcelebdataset + '/',
        data_dir + 'detected_Xtr_ytr_Xt_yt.npz')

In [7]:
type(X)

list

In [8]:
len(X)

11

In [10]:
len(X[0])

45

In [12]:
Xa = np.asarray(X)


In [1]:
Xa.shape

NameError: name 'Xa' is not defined

In [17]:
len(Xa[0])

SyntaxError: invalid syntax (<ipython-input-17-c65e2dacf860>, line 1)

In [20]:
a = np.array([1, 2, 3])
for i in a:
    print(i)

1
2
3


['513',
 '1',
 '10',
 '100',
 '1000',
 '1001',
 '1002',
 '1003',
 '1004',
 '1005',
 '1006']

In [3]:
import numpy as np
x = np.array([1, 2, 3])
y =x

In [4]:
x

array([1, 2, 3])

In [8]:
y = list()

In [29]:
x = [[1, 2], [3, 4]]

In [31]:
x[1:]

[[3, 4]]

In [11]:
y.append(x)

In [12]:
y

[array([[1, 2],
        [3, 4]])]

In [13]:
y.append(x)

In [14]:
y

[array([[1, 2],
        [3, 4]]),
 array([[1, 2],
        [3, 4]])]

In [16]:
y = list()

In [32]:
y.extend(x)

In [33]:
y.extend(x)

In [34]:
y.extend([6, 7])

In [35]:
y

[array([1, 2]),
 array([3, 4]),
 array([1, 2]),
 array([3, 4]),
 6,
 7,
 [1, 2],
 [3, 4],
 [1, 2],
 [3, 4],
 6,
 7]

In [24]:
z =np.asarray(y)

In [25]:
z.shape

(4, 2)

In [38]:
np.full((3,), 1)

array([1, 1, 1])